services:
  cloudreve:
    container_name: cloudreve
    image: cloudreve/cloudreve:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:8004:5212"
    depends_on:
      - database
      - cache
    volumes:
      - /home/docker/cloudreve/uploads:/cloudreve/uploads
      - ./conf.ini:/cloudreve/conf.ini
      - /home/docker/cloudreve/avatar:/cloudreve/avatar
  database:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=cloudreve
      - POSTGRES_USER=cloudreve
      - POSTGRES_DATABASE=cloudreve
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
    volumes:
      - cloudreve-db:/var/lib/postgresql/data
    restart: unless-stopped
  cache:
    image: redis:7-alpine
    restart: unless-stopped
    command: [ redis-server, --save, '60', '1' ]
    volumes:
      - cloudreve-cache:/data
volumes:
  cloudreve-db: {}
  cloudreve-cache: {}